### ISSUE TITLE
403 response code

### ISSUE THREAD

**Issue by ghost** [akshy0407/warp-php-script-refer#1]
I hate python and I think you too so I took a look at how it works on python scripts doing this thing and wrote a swing multithreaded featureful java replacement for it but im testing it and your php script which is way more readable than original one but im keep getting 403 and i have no idea why
Any idea?

**Comment by akshy0407** [comment]
Works fine for me. Please give more details.

**Comment by ghost** [comment]
There is no details no err no response everything null just a 403 response code

**Comment by akshy0407** [comment]
Check for the post fields and install I'd.

**Comment by ghost** [comment]
Are correct

**Comment by ghost** [comment]
does cloudflare blocked iranian ip?

**Comment by akshy0407** [comment]
I check for the warp site it is accessible  from Iran ip .
